name: Trigger Update Pluginmaster

on:
  release:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  TriggerUpdatePluginmaster:
    uses:
      NightmareXIV/MyDalamudPlugins/.github/workflows/Trigger_Update_Pluginmaster.yml@main
    secrets: inherit
